map/static/css/timor.css
map/templates/map/base.html

Remove the static width form the map div, and place all content in a container in the base template

Improve map container

---

map/templates/map/mapview.html

remove unuse css and html elements in mapview.html

remove unuse css and html elements

---

map/static/css/timor.css
map/templates/map/header.html
timor/urls.py

Closes #41 
Fixed at header;
- Display username and user icon if user already log in.
- Added some urls in dropdown menu: "admin", "change password" & "Log out"
- Display "Log in" button if user have not log in.
- Support collapse on it.

suporta collapse no login logout iha header no icon perfil

---

map/templates/map/viajen_form.html

Add datetimepicker to input

---

locale/tet/LC_MESSAGES/django.po
map/templates/map/header.html
requirements.txt
timor/settings.py
timor/urls.py

Closes #60 
- added django-rosetta for the translations support
- git pulll
- pip install requirements.txt
- compile messages
- runserver
-  try switching language

added rosetta translation

---

map/models.py
map/static/css/timor.css
map/templates/map/istoriaviazen_confirm_delete.html
map/templates/map/mapview.html
map/templates/map/phototimor_form.html
map/views.py

Issue: #57 
When user save page istoriaviazen, this page is going page hatam photo before It's going to home page.

Add success url

---

map/static/css/timor.css
map/templates/map/istoriaviazen_confirm_delete.html

Closes #65 
hadia kofirmasaun delete viajen nia style

fixed styling of confirm deleting viajen

---

map/static/css/timor.css
map/templates/map/phototimor_form.html
map/views.py

Interface for upload image

---

map/templates/map/mapview.html
map/urls.py
map/views.py

My suggestion for removing the duplication of code

Suggestion for simpliflying user filter

---

map/templates/map/details.html

- When user click in the detail view, user wants to know more information about the journey history
- Use can click button read more to see more information about the journey.

Add Read more detail view map

---

map/templates/map/mapview.html

Closes #98  
subar ona hatama, troka, no hamoos viajen bainhira user la login.

subar hatama, troka, no hamoos bainhira user la login

---

map/templates/map/mapview.html
map/urls.py

- User needs to login first before user will going to delete, add photo, edit journey and add journey

Add login required

---

map/admin.py

Close issue: #101
- Fo nivel asesu ba uzuario iha admin

Add level access

---

map/templates/map/details.html

- Fixed data target in modal css because when user clicked the modal didn't popup.

Fixed data target in modal css

---

map/urls.py
timor/urls.py

- We had  double media url in the url.py

Removed double media url 

---

map/templates/map/mapview.html

- Added interface for filter by user and added created by user

Filter by user

---

map/templates/map/details.html
map/templates/map/mapview.html

- Moved the title trip to the header.

Moved title to header

---

map/static/css/timor.css
map/templates/map/details.html
map/templates/map/mapview.html

- If user want to see more information, user can click in the read more to see.

Added read more in the mapview

---

map/templates/map/mapview.html

- Added upload date and added h4 to the title

Added upload date and h4

---

map/views.py

- Halo order ba istoria viazen

Order by upload date

---

map/templates/map/mapview.html
map/views.py

- Close issue: #128 
Should ONLY show users who have created a journey.

Add journey creator pk

---

map/static/css/timor.css
map/templates/map/mapview.html

Closes #130 
- Re-organized journey card 
- Removed profile icon on journey card
- Moved important things to the top and fixed indentations

re-organized journey card and fixed indentations

---

map/static/css/timor.css
map/templates/map/mapview.html

Closes #150 
Making a good style of users list, active and hover
Remove font-size on pykafe's logo in footer

good style for users display and remove font-size on pykafes logo

---

map/models.py
map/templates/map/details.html
map/templates/map/fullmapview.html
map/templates/map/mapview.html
map/views.py

Work from Ano and Peter to move geographic object access from the views to the model

Sabadu 01 08

---

map/static/css/timor.css
map/templates/map/header.html

@eraulo 's work on the new header
Changes the background colour to white, and adds dropshadow

Change header bar to white bg with drop shadow

---

map/static/css/timor.css
map/templates/map/mapview.html

Closes #157 
The delete button is to big and no cursor pointer for the delete journey
Make the delete button consistent and adding cursor pointer into the delete journey when the mouse hover into it.
- Mouse pointer should be hovering into delete journey
- The delete button should consistent now

fix delete button style and added cursor pointer into delete journey

---

map/static/css/timor.css
map/templates/map/viajen_form.html

Closes #164 
Description on issue #164 
-  Shows up the image on modal, when the user click the journey image on edit journey

Used modal for view image on edit journey

---

map/static/css/timor.css

Closes #166 
Description on issue #166 
- Added background color to invalid form text
- Try adding or editing Journey with invalid/ empty form.

added background color to invalid form text

---

src/App.vue
vue_ui/views.py

Closes #187
remove comment, prepend media dir and added attribute binding

remove comment, prepend media dir and added attribute binding

---

src/Map.vue

Closes #183 
Show loading feedback
- When first load the page, we don't know if we have any data, so show loading feedback animation to the user.

loading feedback animation

---

src/App.vue
src/Istoria_viazen.vue
src/index.js

Istoria subcomponent

---

src/components/PhotoTimor.vue
vue_ui/views.py

Adding istoria titles to images

Istoria titles in images

---

map/gps_images.py

Use new Pillow coords, fixes #210

---

requirements.txt
timor/settings.py

Added Django version 3.2

---

src/components/PhotoTimor.vue

changed style of the historia title

---

src/App.vue

Remove istoria display from homepage

---

src/components/PhotoTimor.vue
src/index.js
vue_ui/views.py

Closes #no
-  Show username and description in the image
-

added username & description

---

package-lock.json
package.json
src/App.vue
src/Router.js
src/components/PhotoTimor.vue
src/index.js

Vue router

---

src/Router.js
src/Store.js
src/components/Istoria.vue
src/components/Map.vue
src/components/PhotoTimor.vue

Vuex actions to support images in vuex state

Vue vuex actions

---

package-lock.json
yarn.lock

new version of npm

---

src/components/PhotoTimor.vue

Closes #issue_number
- Removing the debug output 
- Photos list page, homepage
- Displaying a loader while the api call is requesting 
- Displaying sorry if the api fails 
-

Displaying loading and sorry

---

map/static/css/timor.css
src/components/AddIstoria.vue

Closes #238
- Followed New design, for details visit this doc https://docs.google.com/presentation/d/14EWwQ-4xXo9PuZCwDFADdyW6I2vnK4zafvAbuiyankU/edit#slide=id.ge838c51280_0_119
- Displaying a nice error on API fail
- Go to add journey form and compare it with the new design

Followed new design layout journey form

---

src/Store.js
src/components/PhotoTimor.vue
vue_ui/urls.py
vue_ui/views.py

Closes #249 
- 
- npm install
- npm run build

Add comment to database

---

map/models.py
package.json
src/Store.js
src/components/PhotoTimor.vue
src/index.js
vue_ui/urls.py
vue_ui/views.py
yarn.lock

Add moment js and request comment from database

---

map/static/css/timor.css
map/templates/map/header.html

Closes #issue_number
- Changed style header to match with marios design
- Removed box-shadow
- Apply the background-color of header to match with the body

changed style header to match with marios design

---

src/components/PhotoTimor.vue

Closes #issue_number
- Changed style of comments image
- Moved the comment form to the top
- Transform text of username to first uppercase style
- Removed sub rows and columns classes
- See in comment page

Re-ordered style of comments image

---

src/components/PhotoTimor.vue

Add username and fullname to Photo Timor
